# Site settings
title: Ben's awesome blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome blog.  Hopefully I can have a better description at
  some point!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: smithbenc
github_username:  bencsmith

# Build settings
markdown: kramdown
